name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  should_run:
    uses: JensDll/should-run/.github/workflows/main.yaml@dev
    with:
      projects: api web db

  api:
    if: fromJSON(needs.should_run.outputs.result).api == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    defaults:
      run:
        working-directory: services/api
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

  web:
    if: fromJSON(needs.should_run.outputs.result).web == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    defaults:
      run:
        working-directory: services/web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

  db:
    if: fromJSON(needs.should_run.outputs.result).db == 'true'
    runs-on: ubuntu-latest
    needs: should_run
    defaults:
      run:
        working-directory: services/web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env
