name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
          GITHUB_ACTIONS_RUNNER_ATTACH_DEBUGGER: true
        run: |
          echo "-----------------------------------"
          ls -la
          echo "-----------------------------------"
          pwd
          echo "-----------------------------------"
          env
