name: On pull request

on:
  pull_request_target:
    branches:
      - main

jobs:
  should-run:
    uses: JensDll/should-run/.github/workflows/main.yaml@main
    with:
      projects: api web db
      diff-filter: dr

  api:
    if: fromJSON(needs.should-run.outputs.result).api == 'true'
    runs-on: ubuntu-latest
    needs: should-run
    defaults:
      run:
        working-directory: services/api
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

  web:
    if: fromJSON(needs.should-run.outputs.result).web == 'true'
    runs-on: ubuntu-latest
    needs: should-run
    defaults:
      run:
        working-directory: services/web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env

  db:
    if: fromJSON(needs.should-run.outputs.result).db == 'true'
    runs-on: ubuntu-latest
    needs: should-run
    defaults:
      run:
        working-directory: services/web
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env
