name: On push

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: |
          ls -la
          pwd
          env

      - name: Making change
        run: echo "github actions" >> test.txt

      - name: Creating a pull request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo
            await github.rest.pulls.create({
              title: 'Test',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'develop',
            });

      - name: Committing changes
        run: |
          git branch -a
          # git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          # git config user.name github-actions
          # git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          # git add .
          # git commit -m "github-actions: test"
          # git push
