name: On push

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: services/api
    steps:
      - name: Debug information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          NEEDS_CONTEXT: ${{ toJSON(needs) }}
        run: env
